export enum AppNode{
  HOME = "home",
  TOURNAMENT = "tournament",
  OPENTOURNAMENT = "open-tournament",
  OPENTOURNAMENTDETAIL = "detail",
  SECURITY="members",
  LOGIN="login",
  SIGNUP="signup",
  REDIRECT_TO_PUBLIC=HOME,
  REDIRECT_TO_AUTHENTICATED=TOURNAMENT,
  REGISTER="register",
  DASHBOARD='dashboard',
  MEMBER="member",
  MEMBERDETAIL="member-detail",
  ADMIN="admin",
  NEWTOURNAMENT="newtournament",
  MANAGETOURNAMENT="managetournament",
  NEXTROUND="nextround",
  UPDATEMATCH="updatematch",
  INFORMATION="information",
}
